<?php
// LAMD/users/user_profile_image.php

// 1. Start Output Buffering immediately to catch any accidental whitespace/errors
ob_start();

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require_once '../config.php';
require_once '../config_session.php';
checkLogin();

// 2. Clean the buffer. This deletes any output generated by config files
ob_end_clean();

header('Content-Type: application/json');

 $user_id = getCurrentUserId();

if (!$user_id) {
    echo json_encode(['success' => false, 'message' => 'User not authenticated.']);
    exit;
}

if (isset($_FILES['profile_image']) && $_FILES['profile_image']['error'] === UPLOAD_ERR_OK) {
    $file = $_FILES['profile_image'];
    $fileExt = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
    
    // Allowed extensions
    $allowed = ['jpg', 'jpeg', 'png', 'gif'];

    if (!in_array($fileExt, $allowed)) {
        echo json_encode(['success' => false, 'message' => 'Invalid file type. Only JPG, JPEG, PNG, GIF allowed.']);
        exit;
    }

    // --- NEW: LIMIT SETTINGS ---
    $maxFileSize = 10097152; // 2MB in bytes (2 * 1024 * 1024)
    $maxWidth = 5000;       // Max width in pixels
    $maxHeight = 5000;      // Max height in pixels

    // 1. Check File Size
    if ($file['size'] > $maxFileSize) {
        echo json_encode(['success' => false, 'message' => 'File size too large. Maximum size is 2MB.']);
        exit;
    }

    // 2. Check Image Dimensions
    // getimagesize requires the temporary file path
    $imageDimensions = getimagesize($file['tmp_name']);
    
    if ($imageDimensions === false) {
        echo json_encode(['success' => false, 'message' => 'File is not a valid image.']);
        exit;
    }

    $width = $imageDimensions[0];
    $height = $imageDimensions[1];

    if ($width > $maxWidth || $height > $maxHeight) {
        echo json_encode(['success' => false, 'message' => "Image dimensions too large. Maximum allowed: {$maxWidth}x{$maxHeight}px."]);
        exit;
    }
    // --- END OF CHECKS ---

    // Generate unique filename
    $newFileName = 'profile_' . $user_id . '_' . time() . '.' . $fileExt;
    
    // Destination path
    $uploadDir = __DIR__ . '/images/'; 
    $destination = $uploadDir . $newFileName;

    // Create directory if it doesn't exist
    if (!is_dir($uploadDir)) {
        // 0777 ensures the server can write to it
        if (!mkdir($uploadDir, 0777, true)) {
            echo json_encode(['success' => false, 'message' => 'Failed to create images folder. Check permissions.']);
            exit;
        }
    }

    // Move file
    if (move_uploaded_file($file['tmp_name'], $destination)) {
        try {
            // Update Database - Save ONLY the filename
            $stmt = $pdo->prepare("UPDATE tbl_users SET profile_image = ? WHERE user_id = ?");
            $stmt->execute([$newFileName, $user_id]);

            echo json_encode([
                'success' => true,
                'message' => 'Image uploaded.',
                'image_url' => 'images/' . $newFileName // Return relative path for JS
            ]);
        } catch (PDOException $e) {
            echo json_encode(['success' => false, 'message' => 'Database error: ' . $e->getMessage()]);
        }
    } else {
        echo json_encode(['success' => false, 'message' => 'Failed to move file. Check folder permissions.']);
    }
} else {
    echo json_encode(['success' => false, 'message' => 'No file uploaded or upload error.']);
}
?>